In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

In [2]:
file_path = Path('../HC/data/price_data_2015_2020_v2.xlsx')
sheets_dict = pd.read_excel(file_path, sheet_name=None, index_col=0)
print(sheets_dict.keys())

dict_keys(['Stock_Indices', 'FX_Rates', 'Bond_Indices', 'Commodities'])

In [3]:
price_df_stock = sheets_dict['Stock_Indices']
price_df_stock

,S&P500,FTSE100,DAX,MSCI_World,MSCI_ACWI,EURO STOXX 50,France_CAC40,NASDAQ100,MSCI_Emerging_mkt,MSCI_Europe,...,FTSE_250,HONGKONG_Index,NIFTY 500,Japan NIKKEI_250,China_SHANGAI_SE_A,China_SHANGAI_SE_B,Swiss Market,MSCI_South-Africa,MSCI_Nigeria,USDollar_Index
Dates,,,,,,,,,,,,,,,,,,,,,
2015-04-30,2085.510000,6960.630000,11454.380000,1778.400000,436.296000,3615.586000,5046.490000,4414.250000,1047.781000,1717.70000,...,17474.63000,28133.000000,6749.650000,19520.010000,4653.824000,1426.321000,9077.120000,1432.46500,417.683000,94.600000
2015-05-29,2107.390000,6984.430000,11413.820000,1779.307000,434.515000,3570.785000,5007.890000,4508.250000,1004.218000,1693.59900,...,18154.42000,27424.190000,6959.850000,20563.150000,4829.125000,1542.183000,9237.790000,1336.08800,412.682000,96.910000
2015-06-30,2063.110000,6520.980000,10944.970000,1735.613000,423.509000,3424.304000,4790.200000,4396.760000,972.254000,1638.87900,...,17531.50000,26250.030000,6897.200000,20235.730000,4479.902000,1462.214000,8780.910000,1368.45800,400.021000,95.490000
2015-07-31,2103.840000,6696.280000,11308.990000,1765.604000,426.781000,3600.687000,5082.610000,4588.910000,901.676000,1689.05100,...,17677.40000,24636.280000,7106.200000,20585.240000,3838.072000,1233.469000,9428.170000,1339.41600,347.363000,97.340000
2015-08-31,1972.180000,6247.940000,10259.460000,1645.430000,396.733000,3269.635000,4652.950000,4274.580000,818.730000,1564.40400,...,17106.36000,21670.580000,6669.350000,18890.480000,3358.812000,1068.061000,8824.560000,1300.33500,342.765000,95.820000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-01-31,3225.520000,7286.010000,12981.970000,2342.414000,558.621000,3640.909000,5806.340000,8991.510000,1062.343000,1738.44200,...,21143.49000,26312.630000,9861.450000,23205.180000,3118.920000,971.410000,10627.880000,1339.98600,177.461000,97.390000
2020-02-28,2954.220000,6580.610000,11890.350000,2141.124000,512.757000,3329.491000,5309.900000,8461.830000,1005.516000,1573.27300,...,19330.92000,26129.930000,9236.050000,21142.960000,3018.360000,922.070000,9831.030000,1223.68000,152.682000,98.130000
2020-03-31,2584.590000,5671.960000,9935.840000,1852.727000,442.346000,2786.904000,4396.120000,7813.500000,848.577000,1341.52200,...,15101.13000,23603.480000,6996.750000,18917.010000,2882.250000,812.170000,9311.920000,1040.93800,108.405000,99.050000
2020-04-30,2912.430000,5901.210000,10861.640000,2052.845000,489.169000,2927.929000,4572.180000,9000.510000,924.937000,1417.46300,...,16454.46000,24643.590000,8012.900000,20193.690000,2997.560000,833.270000,9629.400000,1196.52400,121.463000,99.020000
Total_Return,0.396507,-0.152202,-0.051748,0.154321,0.121186,-0.190192,-0.093988,1.038967,-0.117242,-0.17479,...,-0.05838,-0.124033,0.187158,0.034512,-0.355893,-0.415791,0.060843,-0.16471,-0.709198,0.046723

In [11]:
clean_prices = price_df_stock.replace(0, np.nan)  # remove zeros
log_returns_df = clean_prices.pct_change().dropna()
# log_returns_df = np.log(clean_prices / clean_prices.shift(1)).dropna()
log_returns_df

,S&P500,FTSE100,DAX,MSCI_World,MSCI_ACWI,EURO STOXX 50,France_CAC40,NASDAQ100,MSCI_Emerging_mkt,MSCI_Europe,...,FTSE_250,HONGKONG_Index,NIFTY 500,Japan NIKKEI_250,China_SHANGAI_SE_A,China_SHANGAI_SE_B,Swiss Market,MSCI_South-Africa,MSCI_Nigeria,USDollar_Index
Dates,,,,,,,,,,,,,,,,,,,,,
2015-05-29,0.010491,0.003419,-0.003541,0.000510,-0.004082,-0.012391,-0.007649,0.021295,-0.041576,-0.014031,...,0.038902,-0.025195,0.031142,0.053440,0.037668,0.081231,0.017701,-0.067281,-0.011973,0.024419
2015-06-30,-0.021012,-0.066355,-0.041077,-0.024557,-0.025329,-0.041022,-0.043469,-0.024730,-0.031830,-0.032310,...,-0.034312,-0.042815,-0.009002,-0.015923,-0.072316,-0.051854,-0.049458,0.024227,-0.030680,-0.014653
2015-07-31,0.019742,0.026882,0.033259,0.017280,0.007726,0.051509,0.061043,0.043703,-0.072592,0.030614,...,0.008322,-0.061476,0.030302,0.017272,-0.143269,-0.156437,0.073712,-0.021222,-0.131638,0.019374
2015-08-31,-0.062581,-0.066954,-0.092805,-0.068064,-0.070406,-0.091941,-0.084535,-0.068498,-0.091991,-0.073797,...,-0.032303,-0.120379,-0.061474,-0.082329,-0.124870,-0.134100,-0.064022,-0.029178,-0.013237,-0.015615
2015-09-30,-0.026443,-0.029823,-0.058387,-0.038597,-0.038015,-0.051676,-0.042481,-0.021878,-0.032588,-0.047417,...,-0.024748,-0.038037,-0.003486,-0.079528,-0.048065,-0.016222,-0.035260,-0.030908,0.084667,0.005531
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-01-31,-0.001628,-0.033998,-0.020155,-0.006807,-0.011717,-0.027835,-0.028725,0.029593,-0.046935,-0.025627,...,-0.033812,-0.066589,-0.001124,-0.019083,-0.024112,0.010181,0.001030,-0.022281,0.043778,0.010375
2020-02-28,-0.084110,-0.096816,-0.084087,-0.085933,-0.082102,-0.085533,-0.085500,-0.058909,-0.053492,-0.095010,...,-0.085727,-0.006943,-0.063419,-0.088869,-0.032242,-0.050792,-0.074977,-0.086796,-0.139631,0.007598
2020-03-31,-0.125119,-0.138080,-0.164378,-0.134694,-0.137318,-0.162964,-0.172090,-0.076618,-0.156078,-0.147305,...,-0.218810,-0.096688,-0.242452,-0.105281,-0.045094,-0.119188,-0.052803,-0.149338,-0.289995,0.009375
2020-04-30,0.126844,0.040418,0.093178,0.108013,0.105852,0.050603,0.040049,0.151918,0.089986,0.056608,...,0.089618,0.044066,0.145232,0.067488,0.040007,0.025980,0.034094,0.149467,0.120456,-0.000303
Total_Return,-0.999864,-1.000026,-1.000005,-0.999925,-0.999752,-1.000065,-1.000021,-0.999885,-1.000127,-1.000123,...,-1.000004,-1.000005,-0.999977,-0.999998,-1.000119,-1.000499,-0.999994,-1.000138,-1.005839,-0.999528